import os
import requests
import zipfile
import io
from concurrent.futures import ThreadPoolExecutor

import shutil

# Target the E: drive
STORAGE_DIR = r"E:\training data for quant"
RAW_TICKS_DIR = os.path.join(STORAGE_DIR, "raw_ticks")
RAW_KLINES_DIR = os.path.join(STORAGE_DIR, "raw_klines")

os.makedirs(RAW_TICKS_DIR, exist_ok=True)
os.makedirs(RAW_KLINES_DIR, exist_ok=True)

# Safety threshold: 20 GB in bytes
MIN_FREE_SPACE_BYTES = 20 * 1024 * 1024 * 1024  

# Binance Vision URLs (100% Free, No API Keys needed)
BASE_URL = "https://data.binance.vision/data/spot/monthly"

def check_storage():
    """Returns True if there is enough free space, False otherwise."""
    total, used, free = shutil.disk_usage("E:\\")
    if free < MIN_FREE_SPACE_BYTES:
        free_gb = free / (1024**3)
        print(f"\n🛑 CRITICAL: Storage space critically low ({free_gb:.2f} GB free).")
        print("Halting downloads to protect the 20GB safety buffer on your E: drive.")
        return False
    return True

def download_and_extract(url: str, extract_to: str):
    """Downloads a ZIP file from Binance and extracts the CSV."""
    if not check_storage():
        return False
        
    filename = url.split("/")[-1]
    
    print(f"Downloading {filename}...")
    try:
        response = requests.get(url, stream=True)
        if response.status_code == 404:
            print(f"❌ Not found (data might not exist for this month): {url}")
            return True # Not a failure of the script, just missing data
            
        response.raise_for_status()
        
        # Extract the ZIP directly into the target folder without saving the ZIP to disk
        with zipfile.ZipFile(io.BytesIO(response.content)) as z:
            z.extractall(extract_to)
            print(f"✅ Extracted to {extract_to}")
            return True
            
    except Exception as e:
        print(f"❌ Error downloading {filename}: {e}")
        return False

def get_historical_data(symbol: str, year: int, months: list[int], download_trades: bool = True, download_klines: bool = True):
    """
    Downloads monthly historical data from Binance for a specific coin.
    """
    symbol = symbol.upper()
    
    for month in months:
        if not check_storage():
            break
            
        month_str = f"{month:02d}"
        
        # 1. Download Trades (Tick Data for OFI)
        if download_trades:
            trades_url = f"{BASE_URL}/trades/{symbol}/{symbol}-trades-{year}-{month_str}.zip"
            success = download_and_extract(trades_url, RAW_TICKS_DIR)
            if not success and not check_storage(): break
            
        # 2. Download Klines (1h Candles for EV Model)
        if download_klines:
            klines_url = f"{BASE_URL}/klines/{symbol}/1h/{symbol}-1h-{year}-{month_str}.zip"
            download_and_extract(klines_url, RAW_KLINES_DIR)

if __name__ == "__main__":
    print(f"🚀 Starting Binance Data Downloader targeting {STORAGE_DIR}")
    
    # --- CONFIGURATION ---
    # ARIA is excluded because it only exists on MEXC, not Binance.
    TARGET_COINS = ["BTCUSDT", "SOLUSDT", "ETHUSDT", "BNBUSDT", "DOGEUSDT", "XMRUSDT", "PEPEUSDT"]
    
    # Define the schedule: All of 2025, and Jan-Apr of 2026 
    # (May 2026 data isn't generated by Binance until June 1st)
    DOWNLOAD_SCHEDULE = {
        2025: list(range(1, 13)),  # Months 1 through 12
        2026: list(range(1, 5))    # Months 1 through 4 (Jan to Apr)
    }
    
    for coin in TARGET_COINS:
        if not check_storage():
            break
        print(f"\n{'='*50}\n🌟 STARTING DOWNLOADS FOR {coin}\n{'='*50}")
        for year, months in DOWNLOAD_SCHEDULE.items():
            if not check_storage():
                break
            print(f"\nQueueing downloads for {coin} ({year}) - Months: {months}")
            get_historical_data(
                symbol=coin,
                year=year,
                months=months,
                download_trades=True,
                download_klines=True
            )
            
    print("\n🎉 Script execution finished. Check your E: drive!")
